runtime: python310
entrypoint: streamlit run dashboard/app.py --server.port=$PORT --server.address=0.0.0.0

instance_class: F1

env_variables:
  PYTHONUNBUFFERED: "1"
  
automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
