steps:
  # Build the Streamlit dashboard container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/money-flow-dashboard:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/money-flow-dashboard:latest'
      - '-f'
      - 'Dockerfile.streamlit'
      - '.'
    id: 'build-dashboard'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/money-flow-dashboard:$COMMIT_SHA'
    id: 'push-dashboard'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'money-flow-dashboard'
      - '--image'
      - 'gcr.io/$PROJECT_ID/money-flow-dashboard:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '1'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
    id: 'deploy-dashboard'

  # Deploy Firebase Hosting
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args:
      - 'deploy'
      - '--only'
      - 'hosting,firestore'
      - '--project'
      - '$PROJECT_ID'
    id: 'deploy-hosting'

images:
  - 'gcr.io/$PROJECT_ID/money-flow-dashboard:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/money-flow-dashboard:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
